// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include <pthread.h>
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/concurrency/ThreadManager.h>
#include <thrift/concurrency/PosixThreadFactory.h>
#include <thrift/server/TNonblockingServer.h>

#include "glog/logging.h"
#include "server_handler.h"
#include "flag.h"

#include "server.h"

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;
using namespace ::apache::thrift::concurrency;

using boost::shared_ptr;

namespace tis {

Server::Server() {
    _server = NULL;
}

Server::~Server() {
    if (_server) {
        delete _server;
        _server = NULL;
    }
}

int Server::init() {
    //初始化日志
    FLAGS_logbuflevel = -1;
    google::InitGoogleLogging("se");
    return 0;
}

int Server::run() {
    // processor
    shared_ptr<ServerHandler> handler(new ServerHandler());
    if (0 != handler->init()) {
        LOG(ERROR) << "init se server wrong\n";
        return 1;
    }
    shared_ptr<TProcessor> processor(new SeServerProcessor(handler));

    // protocol
    shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

    // thread pool
    shared_ptr<ThreadManager> threadManager = ThreadManager::newSimpleThreadManager(FLAGS_server_thread_num);
    shared_ptr<PosixThreadFactory> threadFactory(new PosixThreadFactory());
    threadManager->threadFactory(threadFactory);
    threadManager->start();

    // server
    _server = new(std::nothrow) TNonblockingServer(processor,
                                                   protocolFactory,
                                                   FLAGS_server_port,
                                                   threadManager);
    if (NULL == _server) {
        LOG(ERROR) << "uis create nonblocking server error\n";
        return 1;
    }
    _server->serve();

    LOG(INFO) << "uis start ok!\n";
    return 0;
}

void Server::stop() {
    if (_server) {
        _server->stop();
    }
}

}

